-- ============================================================================
-- 12 — Datos de prueba (Trujillo)
-- Requiere: 01 a 11
--
-- Datos FICTICIOS para probar la aplicación, armados desde tu relevamiento.
-- Se puede ejecutar varias veces: no duplica nada.
--
-- Para borrarlos después:  ver el bloque comentado al final.
-- ============================================================================

-- ------------------------------------------------------------- geografía ---
insert into m_departamentos (ubigeo, nombre) values ('13','LA LIBERTAD')
  on conflict (ubigeo) do nothing;
insert into m_provincias (id_departamento, ubigeo, nombre)
  select id_departamento, '1301', 'TRUJILLO' from m_departamentos where ubigeo='13'
  on conflict (ubigeo) do nothing;
insert into m_zonas (nombre) values ('Trujillo'), ('Chiclayo'), ('Lima'), ('Arequipa')
  on conflict (nombre) do nothing;

insert into m_distritos (id_provincia, id_zona, ubigeo, nombre, con_cobertura) values
  ((select id_provincia from m_provincias where ubigeo='1301'), (select id_zona from m_zonas where nombre='Trujillo'), '130101', 'ALTO_TRUJILLO', true),
  ((select id_provincia from m_provincias where ubigeo='1301'), (select id_zona from m_zonas where nombre='Trujillo'), '130102', 'EL_PORVENIR', true),
  ((select id_provincia from m_provincias where ubigeo='1301'), (select id_zona from m_zonas where nombre='Trujillo'), '130103', 'FLORENCIA_DE_MORA', true),
  ((select id_provincia from m_provincias where ubigeo='1301'), (select id_zona from m_zonas where nombre='Trujillo'), '130104', 'LA_ESPERANZA', true),
  ((select id_provincia from m_provincias where ubigeo='1301'), (select id_zona from m_zonas where nombre='Trujillo'), '130105', 'MOCHE', true),
  ((select id_provincia from m_provincias where ubigeo='1301'), (select id_zona from m_zonas where nombre='Trujillo'), '130106', 'TRUJILLO', true)
on conflict (ubigeo) do nothing;

-- ---------------------------------------------------------- ferreterías ---
-- Falta una restricción: sin ella se pueden crear dos ferreterías con el
-- mismo nombre, y el cargador no sabría a cuál asociar los precios.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'uq_ferreteria_nombre') then
    alter table m_ferreterias add constraint uq_ferreteria_nombre unique (nombre);
  end if;
end $$;

insert into m_ferreterias (nombre) values
  ('2BOX'),
  ('FERRETERIA ALCA'),
  ('FERRETERIA BETO'),
  ('FERRETERIA EGIPTO'),
  ('FERRETERIA HIRINA'),
  ('FERRETERIA LIDER'),
  ('FERRETERIA MACONSA'),
  ('FERRONOR_TRUJILLO'),
  ('GRUPO FERRETERO DEL NORTE'),
  ('INVERSIONES LANTANA'),
  ('LA ROCA EIRL'),
  ('LA SOLUCION'),
  ('LAS PALMERAS'),
  ('MERI CONSTRUCCIONES'),
  ('OMEGA FERRETEROS'),
  ('TACORITA E.I.R.L.')
on conflict (nombre) do nothing;

insert into m_sedes (id_ferreteria, codigo, nombre, id_distrito, latitud, longitud) values
  ((select id_ferreteria from m_ferreterias where nombre='LAS PALMERAS'), 'TRUJ001', 'LAS PALMERAS', (select id_distrito from m_distritos where nombre='LA_ESPERANZA'), -8.047036, -79.049882),
  ((select id_ferreteria from m_ferreterias where nombre='FERRONOR_TRUJILLO'), 'TRUJ002', 'FERRONOR_TRUJILLO', (select id_distrito from m_distritos where nombre='EL_PORVENIR'), -8.0936244, -79.003489),
  ((select id_ferreteria from m_ferreterias where nombre='FERRETERIA HIRINA'), 'TRUJ003', 'FERRETERIA HIRINA', (select id_distrito from m_distritos where nombre='LA_ESPERANZA'), -8.037806, -79.072389),
  ((select id_ferreteria from m_ferreterias where nombre='INVERSIONES LANTANA'), 'TRUJ004', 'INVERSIONES LANTANA', (select id_distrito from m_distritos where nombre='LA_ESPERANZA'), -8.034663, -79.068044),
  ((select id_ferreteria from m_ferreterias where nombre='TACORITA E.I.R.L.'), 'TRUJ005', 'TACORITA E.I.R.L.', (select id_distrito from m_distritos where nombre='LA_ESPERANZA'), -8.0530196, -79.071593),
  ((select id_ferreteria from m_ferreterias where nombre='FERRETERIA LIDER'), 'TRUJ006', 'FERRETERIA LIDER', (select id_distrito from m_distritos where nombre='TRUJILLO'), -8.1125038, -79.0061638),
  ((select id_ferreteria from m_ferreterias where nombre='FERRETERIA ALCA'), 'TRUJ007', 'FERRETERIA ALCA', (select id_distrito from m_distritos where nombre='TRUJILLO'), -8.113078, -79.013299),
  ((select id_ferreteria from m_ferreterias where nombre='FERRETERIA MACONSA'), 'TRUJ008', 'FERRETERIA MACONSA', (select id_distrito from m_distritos where nombre='LA_ESPERANZA'), -8.0530089, -79.0550378),
  ((select id_ferreteria from m_ferreterias where nombre='FERRETERIA EGIPTO'), 'TRUJ009', 'FERRETERIA EGIPTO', (select id_distrito from m_distritos where nombre='FLORENCIA_DE_MORA'), -8.0748747, -79.0576209),
  ((select id_ferreteria from m_ferreterias where nombre='2BOX'), 'TRUJ010', '2BOX', (select id_distrito from m_distritos where nombre='ALTO_TRUJILLO'), null, null),
  ((select id_ferreteria from m_ferreterias where nombre='GRUPO FERRETERO DEL NORTE'), 'TRUJ011', 'GRUPO FERRETERO DEL NORTE', (select id_distrito from m_distritos where nombre='TRUJILLO'), -8.112786, -79.00973),
  ((select id_ferreteria from m_ferreterias where nombre='LA ROCA EIRL'), 'TRUJ012', 'LA ROCA EIRL', (select id_distrito from m_distritos where nombre='TRUJILLO'), -8.110865, -79.0129),
  ((select id_ferreteria from m_ferreterias where nombre='LA SOLUCION'), 'TRUJ013', 'LA SOLUCION', (select id_distrito from m_distritos where nombre='EL_PORVENIR'), -8.083231, -79.001841),
  ((select id_ferreteria from m_ferreterias where nombre='MERI CONSTRUCCIONES'), 'TRUJ014', 'MERI CONSTRUCCIONES', (select id_distrito from m_distritos where nombre='LA_ESPERANZA'), -8.0657802, -79.0675117),
  ((select id_ferreteria from m_ferreterias where nombre='OMEGA FERRETEROS'), 'TRUJ015', 'OMEGA FERRETEROS', (select id_distrito from m_distritos where nombre='ALTO_TRUJILLO'), -8.0759, -79.020228),
  ((select id_ferreteria from m_ferreterias where nombre='FERRETERIA BETO'), 'TRUJ016', 'FERRETERIA BETO', (select id_distrito from m_distritos where nombre='MOCHE'), -8.1718465, -79.0112818)
on conflict (codigo) do nothing;

-- ------------------------------------------------------------ catálogos ---
insert into m_tipos_pago (nombre) values
  ('Transferencia'), ('Yape o Plin'), ('Efectivo en tienda'), ('Tarjeta'), ('Contraentrega')
  on conflict (nombre) do nothing;

insert into m_motivos_perdida (etapa, nombre, automatico) values
  ('cotizado','Muy caro', false),
  ('cotizado','No acepta la modalidad de pago', false),
  ('cotizado','Pactó compra y no transfirió', false),
  ('cotizado','Obra no activa, solo mapea precios', false),
  ('cotizado','Compró en otro lado', false),
  ('asesor','No envió lista de materiales', false),
  ('asesor','Fuera de cobertura', false),
  ('cotizado','Sin respuesta del cliente', true)
  on conflict (nombre) do nothing;

insert into m_categorias (nombre, computa_toneladas) values
  ('AGREGADOS', false),
  ('ALAMBRE', true),
  ('CEMENTO', false),
  ('CLAVOS', true),
  ('FIERRO', true),
  ('LADRILLO', false)
on conflict (nombre) do nothing;

insert into m_unidades_medida (codigo, nombre) values
  ('VAR','Varilla de 9 m'), ('BOL','Bolsa de 42.5 kg'), ('KG','Kilogramo'),
  ('M3','Metro cúbico'), ('UND','Unidad')
  on conflict (codigo) do nothing;

insert into m_marcas (nombre) values
  ('ACEROS AREQUIPA'),
  ('CERAMIREX'),
  ('CHICLAYANO'),
  ('DIAMANTE'),
  ('FORTES'),
  ('INKA'),
  ('INKAFORTE'),
  ('ITAL'),
  ('LARK'),
  ('METALICK'),
  ('MOCHICA'),
  ('PACASMAYO'),
  ('PIRAMIDE'),
  ('PRODAC'),
  ('SIDERPERU'),
  ('SIN MARCA'),
  ('TAYSON'),
  ('TUMI'),
  ('YURA')
on conflict (nombre) do nothing;

insert into m_productos (id_categoria, nombre) values
  ((select id_categoria from m_categorias where nombre='ALAMBRE'), 'ALAMBRE #16'),
  ((select id_categoria from m_categorias where nombre='ALAMBRE'), 'ALAMBRE #8'),
  ((select id_categoria from m_categorias where nombre='AGREGADOS'), 'ARENA GRUESA'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 1"'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 1.3/8"'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 1/2"'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 12mm'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 3/4"'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 3/8"'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 5/8"'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 6mm'),
  ((select id_categoria from m_categorias where nombre='FIERRO'), 'BC 8mm'),
  ((select id_categoria from m_categorias where nombre='CLAVOS'), 'CLAVO 1"'),
  ((select id_categoria from m_categorias where nombre='CLAVOS'), 'CLAVO 2 1/2"'),
  ((select id_categoria from m_categorias where nombre='CLAVOS'), 'CLAVO 2"'),
  ((select id_categoria from m_categorias where nombre='CLAVOS'), 'CLAVO 3"'),
  ((select id_categoria from m_categorias where nombre='CLAVOS'), 'CLAVO 4"'),
  ((select id_categoria from m_categorias where nombre='AGREGADOS'), 'GRAVILLA 1/2'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'INKA ANTISALITRE(AZUL)'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'INKA ULTRA RESISTENTE(ROJO)'),
  ((select id_categoria from m_categorias where nombre='LADRILLO'), 'KING KONG 18H'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'MOCHICA ANTISALITRE(AZUL)'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'MOCHICA GU(ROJO)'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'PACASMAYO EXTRAFORTE(ROJO)'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'PACASMAYO FORTIMAX(AZUL)'),
  ((select id_categoria from m_categorias where nombre='LADRILLO'), 'PANDERETA'),
  ((select id_categoria from m_categorias where nombre='LADRILLO'), 'TECHO HUECO 12'),
  ((select id_categoria from m_categorias where nombre='LADRILLO'), 'TECHO HUECO 15'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'YURA ANTISALITRE MS(CELESTE)'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'YURA FRONTERA GU(ROJO)'),
  ((select id_categoria from m_categorias where nombre='CEMENTO'), 'YURAMAX(AZUL)')
on conflict (nombre) do nothing;

insert into m_skus (id_producto, id_marca, id_unidad_medida, peso_kg) values
  ((select id_producto from m_productos where nombre='ALAMBRE #16'), (select id_marca from m_marcas where nombre='ACEROS AREQUIPA'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='ALAMBRE #16'), (select id_marca from m_marcas where nombre='PRODAC'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='ALAMBRE #16'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='ALAMBRE #8'), (select id_marca from m_marcas where nombre='ACEROS AREQUIPA'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='ALAMBRE #8'), (select id_marca from m_marcas where nombre='PRODAC'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='ALAMBRE #8'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='ARENA GRUESA'), (select id_marca from m_marcas where nombre='SIN MARCA'), (select id_unidad_medida from m_unidades_medida where codigo='M3'), null),
  ((select id_producto from m_productos where nombre='BC 1"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 35.76),
  ((select id_producto from m_productos where nombre='BC 1.3/8"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 5.04),
  ((select id_producto from m_productos where nombre='BC 1/2"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 8.95),
  ((select id_producto from m_productos where nombre='BC 12mm'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 7.99),
  ((select id_producto from m_productos where nombre='BC 3/4"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 20.12),
  ((select id_producto from m_productos where nombre='BC 3/8"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 5.04),
  ((select id_producto from m_productos where nombre='BC 5/8"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 13.97),
  ((select id_producto from m_productos where nombre='BC 6mm'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 2.0),
  ((select id_producto from m_productos where nombre='BC 8mm'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='VAR'), 3.55),
  ((select id_producto from m_productos where nombre='CLAVO 1"'), (select id_marca from m_marcas where nombre='METALICK'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 1"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 2 1/2"'), (select id_marca from m_marcas where nombre='ACEROS AREQUIPA'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 2 1/2"'), (select id_marca from m_marcas where nombre='PRODAC'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 2 1/2"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 2"'), (select id_marca from m_marcas where nombre='ACEROS AREQUIPA'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 2"'), (select id_marca from m_marcas where nombre='PRODAC'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 2"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 3"'), (select id_marca from m_marcas where nombre='ACEROS AREQUIPA'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 3"'), (select id_marca from m_marcas where nombre='PRODAC'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 3"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 4"'), (select id_marca from m_marcas where nombre='ACEROS AREQUIPA'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 4"'), (select id_marca from m_marcas where nombre='PRODAC'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='CLAVO 4"'), (select id_marca from m_marcas where nombre='SIDERPERU'), (select id_unidad_medida from m_unidades_medida where codigo='KG'), 1.0),
  ((select id_producto from m_productos where nombre='GRAVILLA 1/2'), (select id_marca from m_marcas where nombre='SIN MARCA'), (select id_unidad_medida from m_unidades_medida where codigo='M3'), null),
  ((select id_producto from m_productos where nombre='INKA ANTISALITRE(AZUL)'), (select id_marca from m_marcas where nombre='INKA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='INKA ULTRA RESISTENTE(ROJO)'), (select id_marca from m_marcas where nombre='INKA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='KING KONG 18H'), (select id_marca from m_marcas where nombre='CERAMIREX'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='KING KONG 18H'), (select id_marca from m_marcas where nombre='DIAMANTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='KING KONG 18H'), (select id_marca from m_marcas where nombre='FORTES'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='KING KONG 18H'), (select id_marca from m_marcas where nombre='INKAFORTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='KING KONG 18H'), (select id_marca from m_marcas where nombre='LARK'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='KING KONG 18H'), (select id_marca from m_marcas where nombre='TAYSON'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='MOCHICA ANTISALITRE(AZUL)'), (select id_marca from m_marcas where nombre='MOCHICA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='MOCHICA GU(ROJO)'), (select id_marca from m_marcas where nombre='MOCHICA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='PACASMAYO EXTRAFORTE(ROJO)'), (select id_marca from m_marcas where nombre='PACASMAYO'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='PACASMAYO FORTIMAX(AZUL)'), (select id_marca from m_marcas where nombre='PACASMAYO'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='CERAMIREX'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='CHICLAYANO'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='DIAMANTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='FORTES'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='INKAFORTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='LARK'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='TAYSON'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='PANDERETA'), (select id_marca from m_marcas where nombre='TUMI'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 12'), (select id_marca from m_marcas where nombre='DIAMANTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 12'), (select id_marca from m_marcas where nombre='FORTES'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 12'), (select id_marca from m_marcas where nombre='INKAFORTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 12'), (select id_marca from m_marcas where nombre='ITAL'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 12'), (select id_marca from m_marcas where nombre='LARK'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='DIAMANTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='FORTES'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='INKAFORTE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='ITAL'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='LARK'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='PIRAMIDE'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='TECHO HUECO 15'), (select id_marca from m_marcas where nombre='TUMI'), (select id_unidad_medida from m_unidades_medida where codigo='UND'), null),
  ((select id_producto from m_productos where nombre='YURA ANTISALITRE MS(CELESTE)'), (select id_marca from m_marcas where nombre='YURA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='YURA FRONTERA GU(ROJO)'), (select id_marca from m_marcas where nombre='YURA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5),
  ((select id_producto from m_productos where nombre='YURAMAX(AZUL)'), (select id_marca from m_marcas where nombre='YURA'), (select id_unidad_medida from m_unidades_medida where codigo='BOL'), 42.5)
on conflict (id_producto, id_marca, id_unidad_medida) do nothing;

-- -------------------------------------------------------------- precios ---
insert into m_precios (id_sede, id_sku, precio, fuente) values
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='ACEROS AREQUIPA'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.6, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.1, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 3.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 5.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #16' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='ACEROS AREQUIPA'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.6, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.1, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 3.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 5.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ALAMBRE #8' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='ARENA GRUESA' and m.nombre='SIN MARCA'), 35.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='GRAVILLA 1/2' and m.nombre='SIN MARCA'), 45.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1"' and m.nombre='SIDERPERU'), 133.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1"' and m.nombre='SIDERPERU'), 136.53, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1"' and m.nombre='SIDERPERU'), 135.22, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1"' and m.nombre='SIDERPERU'), 140.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1"' and m.nombre='SIDERPERU'), 140.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1"' and m.nombre='SIDERPERU'), 134.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1.3/8"' and m.nombre='SIDERPERU'), 351.44, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 33.33, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 33.12, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.13, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.15, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 33.81, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.03, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 33.7, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 34.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 1/2"' and m.nombre='SIDERPERU'), 33.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 29.74, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.08, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.46, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.85, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.17, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.37, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.1, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 31.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 12mm' and m.nombre='SIDERPERU'), 30.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 75.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 77.64, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 77.45, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 76.89, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 77.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 76.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 80.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 78.14, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/4"' and m.nombre='SIDERPERU'), 76.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 18.59, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 18.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 19.04, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 19.55, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 18.85, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 18.98, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 18.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 19.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 19.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 19.19, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 19.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 3/8"' and m.nombre='SIDERPERU'), 18.7, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 51.54, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.13, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.79, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.85, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.29, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.63, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 53.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 53.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 53.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 5/8"' and m.nombre='SIDERPERU'), 52.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.49, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.58, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.67, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 8.25, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.6, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 8.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.7, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 8.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 8.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.99, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 8.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 6mm' and m.nombre='SIDERPERU'), 7.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 13.42, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 13.58, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 13.75, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 14.35, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 13.62, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 14.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 15.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 14.6, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 14.19, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 14.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='BC 8mm' and m.nombre='SIDERPERU'), 13.6, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 1"' and m.nombre='SIDERPERU'), 5.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 1"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 1"' and m.nombre='SIDERPERU'), 10.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='ACEROS AREQUIPA'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='PRODAC'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 5.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 3.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2 1/2"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='ACEROS AREQUIPA'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='PRODAC'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='PRODAC'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 5.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 3.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 2"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='ACEROS AREQUIPA'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='PRODAC'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 5.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 3.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 3"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='ACEROS AREQUIPA'), 4.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='PRODAC'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 5.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 4.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 3.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 4.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='CLAVO 4"' and m.nombre='SIDERPERU'), 5.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ANTISALITRE(AZUL)' and m.nombre='INKA'), 32.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ANTISALITRE(AZUL)' and m.nombre='INKA'), 33.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ANTISALITRE(AZUL)' and m.nombre='INKA'), 32.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ULTRA RESISTENTE(ROJO)' and m.nombre='INKA'), 29.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ULTRA RESISTENTE(ROJO)' and m.nombre='INKA'), 29.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ULTRA RESISTENTE(ROJO)' and m.nombre='INKA'), 29.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='INKA ULTRA RESISTENTE(ROJO)' and m.nombre='INKA'), 29.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 33.7, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 33.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 33.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 34.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 34.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 34.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 34.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA ANTISALITRE(AZUL)' and m.nombre='MOCHICA'), 34.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 30.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 29.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 30.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 30.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 30.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 30.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 30.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='MOCHICA GU(ROJO)' and m.nombre='MOCHICA'), 29.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.6, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.9, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 32.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO EXTRAFORTE(ROJO)' and m.nombre='PACASMAYO'), 31.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 34.7, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 34.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 34.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 34.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 34.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 35.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 35.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 35.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 35.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 35.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PACASMAYO FORTIMAX(AZUL)' and m.nombre='PACASMAYO'), 34.8, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='CERAMIREX'), 0.89, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='CERAMIREX'), 0.93, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='CERAMIREX'), 0.98, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.92, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.98, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.93, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.93, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.95, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.95, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.97, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='FORTES'), 0.95, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='INKAFORTE'), 1.1, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='INKAFORTE'), 1.12, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.15, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.32, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ008'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.28, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='LARK'), 1.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='TAYSON'), 1.05, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='TAYSON'), 1.12, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='TAYSON'), 1.16, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='KING KONG 18H' and m.nombre='TAYSON'), 1.14, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='CERAMIREX'), 0.85, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='CHICLAYANO'), 0.83, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='FORTES'), 0.85, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='INKAFORTE'), 0.78, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='INKAFORTE'), 0.85, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='LARK'), 0.95, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='LARK'), 0.98, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ002'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TAYSON'), 0.78, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TAYSON'), 0.7, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TAYSON'), 0.97, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TUMI'), 0.76, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TUMI'), 0.86, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TUMI'), 0.77, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='PANDERETA' and m.nombre='TUMI'), 0.75, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='INKAFORTE'), 3.15, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='ITAL'), 3.1, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='ITAL'), 3.1, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='ITAL'), 3.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ007'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='ITAL'), 2.94, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='ITAL'), 3.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='ITAL'), 3.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='LARK'), 3.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='LARK'), 3.0, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='LARK'), 3.35, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='LARK'), 3.65, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 12' and m.nombre='LARK'), 3.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='INKAFORTE'), 3.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='ITAL'), 3.2, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ006'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='ITAL'), 3.42, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ011'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='ITAL'), 3.3, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='ITAL'), 3.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ001'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='LARK'), 3.4, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ004'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='LARK'), 3.5, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ016'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='LARK'), 3.05, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ012'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='LARK'), 3.45, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ015'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='LARK'), 3.75, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ013'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='LARK'), 3.45, 'relevamiento'),
  ((select id_sede from m_sedes where codigo='TRUJ005'), (select s.id_sku from m_skus s join m_productos p on p.id_producto=s.id_producto join m_marcas m on m.id_marca=s.id_marca where p.nombre='TECHO HUECO 15' and m.nombre='PIRAMIDE'), 3.4, 'relevamiento')
on conflict (id_sede, id_sku) do nothing;

-- 264 precios cargados. 102 quedaron fuera porque su
-- ferretería no está en el maestro de sedes (GOMESUR, MORENO Y HERMANOS,
-- GLOBAL DRAGON, JVV INGENIEROS, FERRETERIA TORRES y FERPERU).
-- Cuando tengas sus direcciones, se cargan y esos precios entran solos.

-- --------------------------------------------------------------- clientes ---
insert into m_clientes (telefono, nombre, tipo_documento, numero_documento, id_tipo_cliente) values
  ('+51912345678','Constructora Los Andes SAC','RUC','20601234567',
    (select id_tipo_cliente from m_tipos_cliente where nombre='Constructora')),
  ('+51987654321','Juan Pérez Rodríguez','DNI','45678912',
    (select id_tipo_cliente from m_tipos_cliente where nombre='Dueño de obra')),
  ('+51965432198','Maestro Luis Vargas','DNI','41258963',
    (select id_tipo_cliente from m_tipos_cliente where nombre='Maestro de obra'))
  on conflict (telefono) do nothing;


-- ============================================================================
-- PARA BORRAR TODO ESTO (solo en el proyecto de desarrollo):
--
--   delete from fact_ventas_detalle;      delete from fact_ventas;
--   delete from fact_cotizaciones_detalle; delete from fact_cotizaciones;
--   delete from fact_negociaciones;       delete from m_clientes;
--   delete from m_precios;                delete from m_skus;
--   delete from m_productos;              delete from m_sedes;
--   delete from m_ferreterias;            delete from m_distritos;
-- ============================================================================
